services:

  users-v1:
    build:
      context: .
      dockerfile: docker/service/Dockerfile
    image: ghcr.io/barpav/msg-users:v1
    container_name: msg-users-v1
    environment:
      - MSG_STORAGE_HOST=storage-users-v1
      - MSG_SESSIONS_HOST=sessions-v1
      - MSG_FILES_STAT_HOST=broker
    expose:
      - 9000
    ports:
      - 8080:8080
    depends_on:
      storage-users-v1:
        condition: service_healthy
      broker:
        condition: service_healthy

  storage-users-v1:
    build:
      context: docker/storage
    image: ghcr.io/barpav/msg-storage-users:v1
    container_name: msg-storage-users-v1
    environment:
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 2s
      retries: 5
  
  sessions-v1:
    image: ghcr.io/barpav/msg-sessions:v1
    container_name: msg-sessions-v1
    environment:
      - MSG_STORAGE_HOST=storage-sessions-v1
      - MSG_USERS_HOST=users-v1
    expose:
      - 8080
      - 9000
    ports:
      - 8081:8080
    depends_on:
      storage-sessions-v1:
        condition: service_healthy
      users-v1:
        condition: service_started
  
  storage-sessions-v1:
    image: redis:alpine3.18
    container_name: msg-storage-sessions-v1
    expose:
      - 6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: 1s
      timeout: 2s
      retries: 5
  
  broker:
    image: rabbitmq:3.9.29-alpine
    container_name: msg-broker
    expose:
      - 5672
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1G