services:

  sessions-v1:
    image: ghcr.io/barpav/msg-sessions:v1
    container_name: msg-sessions-v1
    environment:
      - MSG_HTTP_PORT=8081
      - MSG_GRPC_PORT=9001
    depends_on:
      storage-sessions-v1:
        condition: service_healthy
    network_mode: host
  
  storage-sessions-v1:
    image: redis:alpine3.18
    container_name: msg-storage-sessions-v1
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: 1s
      timeout: 2s
      retries: 5
    network_mode: host
  
  broker:
    image: rabbitmq:3.9.29-alpine
    container_name: msg-broker
    ports:
    - 5672:5672
    expose:
      - 5672
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1G